name: Publish Library in NPM
on:
  release:
    types:
      - created

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check the project
      uses: actions/setup-node@v1
      with:
        node-version: '18.0.0'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.0.0'
          cache: 'npm'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run build
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}